feat: add retry and http client plugins
smithy-lang/smithy-swift pull request #671
Opened 2024-02-22 01:12 UTC by AndrewFossAWS

## Issue \#

## Description of changes

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-26 21:32 UTC, AndrewFossAWS commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
> -                    val customPlugins: MutableList<Plugin> = mutableListOf()
There weren't any plugins that fell under custom plugins. It should only be default plugins.

2024-02-26 21:33 UTC, AndrewFossAWS commented on Sources/ClientRuntime/Plugins/DefaultClientPlugin.swift
> +            var httpClientConfiguration = DefaultSDKRuntimeConfiguration<DefaultRetryStrategy, DefaultRetryErrorInfoProvider>
> Will the DefaultSDKRuntimeConfiguration struct used here be refactored down the line?

Yes. I will try to send out a PR later this week.

2024-02-27 20:21 UTC, syall approved these changes

2024-02-27 20:21 UTC, syall commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
> +            writer.write("let config = try \$L()", serviceConfig.typeName)
Nice change 👍 . Are these set anywhere else right now?

2024-02-29 17:44 UTC, AndrewFossAWS commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
> +            writer.write("let config = try \$L()", serviceConfig.typeName)
Nope :)

2024-02-29 18:19 UTC, sichanyoo requested changes
Just need swiftlint warnings (10) taken care of, should be good afterwards.

2024-03-01 18:23 UTC, sichanyoo approved these changes

2024-03-01 18:43 UTC, merged