feat: overhaul protocol test generation to use actual client
smithy-lang/smithy-swift pull request #767
Opened 2024-06-25 18:01 UTC by dayaffe

## Issue \#

## Description of changes

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-25 18:47 UTC, dayaffe commented on Sources/SmithyTestUtil/RequestTestUtil/HttpRequestTestBase.swift
> +            XCTAssertTrue(valueExists,
Test was failing as `nil != []` but these should be equivalent

2024-06-25 18:49 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/endpoints/EndpointResolverGenerator.kt
> +    private fun renderStaticResolver(writer: SwiftWriter) {
Static Resolver will be used by tests but are also part of SRA to allow users to bypass endpoint resolution and provide their own endpoint

2024-06-25 18:50 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
> +        }
Tests were failing due to a missing preceding or ending `/`

2024-06-25 18:51 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
> +        var hostValue = if (test.host.isPresent && test.host.get() != "") test.host.get() else "example.com"
Provide a host (example.com) to be used during tests that do not specify one

2024-06-25 18:51 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
> +    private fun renderClientBlock(test: HttpRequestTestCase) {
This block renders the client call and its config options

2024-06-25 18:51 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
> +        writer.write("config.httpClientEngine = ProtocolTestClient()")
Use the ProtocolTestClient() as the httpClientEngine to ensure we get the request back and never send it

2024-06-25 18:52 UTC, dayaffe commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
> +        writer.write("config.idempotencyTokenGenerator = ProtocolTestIdempotencyTokenGenerator()")
Use our own token generator to ensure the expected test token will get generated during middleware execution

2024-06-25 18:54 UTC, dayaffe commented on Sources/SmithyTestUtil/RequestTestUtil/HttpRequestTestBase.swift
> +        }
There is an edge case where the SignerMiddleware has already read an unseekable stream. In which case by the time all middlewares are executed we cannot re-read the data. In that case let's check if the actual and expected stream lengths are the same.

Note: This comparison should only fail if the actualStream.position == actualStream.length and !actualStream.isSeekable

2024-06-25 18:54 UTC, dayaffe commented on Sources/SmithyTestUtil/ProtocolTestClient.swift
> +        throw TestCheckError.actual(request)
throwing an error with the request will allow tests to do checks against the result

2024-06-25 18:55 UTC, dayaffe commented on Sources/ClientRuntime/Networking/Http/Middlewares/SignerMiddleware.swift
> +        }
SHA256Middleware if executed will set this attribute to be picked up by the SignerMiddleware and put into the signing properties

2024-07-02 19:46 UTC, jbelkins commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/endpoints/EndpointResolverGenerator.kt
> +        writer.openBlock("public struct StaticEndpointResolver: EndpointResolver {", "}") {
Can we provide a reusable static endpoint resolver?

The only difference between this endpoint resolver for each service is that the `resolve` method takes that client's `EndpointParams` so we can make that type generic in a reusable static endpoint resolver, then simply use a typedef in each client to provide a specialized endpoint resolver.

2024-07-02 19:47 UTC, jbelkins requested changes
See my question about a reusable static endpoint resolver.

Other than that, all is good.

2024-07-05 15:41 UTC, jbelkins approved these changes

2024-07-05 21:05 UTC, merged