feat: Smoke Tests V2
smithy-lang/smithy-swift pull request #841
Opened 2024-10-16 18:58 UTC by sichanyoo

## Issue \#

1779

## Description of changes

- Adds the smoke test code generator for generic Smithy spec, whose behaviors can be customized via method overrides in a child class.

## Scope

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-16 21:55 UTC, sichanyoo reviewed
Comments for reviewers.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/DirectedSwiftCodegen.kt
> +            generateSmokeTests(ctx)
This is _the_ place where smoke test generation gets triggered

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPBindingProtocolGenerator.kt
> +    }
This concrete implementation generates smoke tests according to generic Smithy spec.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ProtocolGenerator.kt
> +    fun generateSmokeTests(ctx: GenerationContext)
This gets implemented both in smithy-swift and aws-sdk-swift, each generating tests in generic Smithy way vs. AWS way, respectively.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +package software.amazon.smithy.swift.codegen.integration
Generates smoke tests according to generic Smithy spec. A child class in aws-sdk-swift extends this class to customize AWS specific logic by overriding vendor specific methods.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +    }
Test result line produced here follows the [TAP protocol](https://testanything.org/tap-specification.html) as well as additional restrictions defined in SEPs.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +    }
`renderDoCatchBlock()` contains the logic for test result & error handling codegen.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +    }
The vendor params are custom client config fields included for a given service client. In our case, all the config fields added to service clients in aws-sdk-swift.

2024-10-16 21:55 UTC, sichanyoo commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/swiftmodules/ClientRuntimeTypes.kt
>          val InterceptorProvider = runtimeSymbol("InterceptorProvider", SwiftDeclaration.PROTOCOL)
This and below change are for test files that need to import these.

2024-10-28 16:42 UTC, jbelkins approved these changes
All of this is good.

I'm tempted to include a codegen switch to turn smoke test generation on/off, but as long as the tests are .gitignored and they remain reasonably small, I'm okay with generating them every time for now.

2024-10-29 15:34 UTC, jbelkins commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +    //    }
remove commented code

2024-10-29 15:36 UTC, jbelkins requested changes
one minor code cleanup

2024-10-29 15:36 UTC, jbelkins commented on smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
> +    //    }
remove commented code

2024-10-29 16:41 UTC, jbelkins approved these changes

2024-10-29 16:43 UTC, merged